[project]
authors = ["segfault_magnet"]
entry = "main.sw"
license = "Apache-2.0"
name = "some_contract"

[dependencies]

[patch.'https://github.com/fuellabs/sway']
std = { git = "https://github.com/fuellabs/sway", branch = "feat/transaction-policies" }